const vocabBank = [
  { id: 'house', level: 'A1', cat: 'Home', w: 'HOUSE', a: ['Casa', 'Mesa', 'Puerta', 'Calle'], c: 'Casa' },
  { id: 'book', level: 'A1', cat: 'Study', w: 'BOOK', a: ['Libro', 'Cuaderno', 'Lápiz', 'Clase'], c: 'Libro' },
  { id: 'water', level: 'A1', cat: 'Daily life', w: 'WATER', a: ['Agua', 'Comida', 'Vaso', 'Jugo'], c: 'Agua' },
  { id: 'friend', level: 'A1', cat: 'People', w: 'FRIEND', a: ['Amigo/a', 'Familia', 'Vecino/a', 'Profesor/a'], c: 'Amigo/a' },
  { id: 'learn', level: 'A1', cat: 'Actions', w: 'LEARN', a: ['Aprender', 'Escuchar', 'Escribir', 'Leer'], c: 'Aprender' },
  { id: 'school', level: 'A1', cat: 'Study', w: 'SCHOOL', a: ['Escuela', 'Oficina', 'Tienda', 'Parque'], c: 'Escuela' },
  { id: 'morning', level: 'A1', cat: 'Time', w: 'MORNING', a: ['Mañana', 'Tarde', 'Noche', 'Semana'], c: 'Mañana' },
  { id: 'happy', level: 'A1', cat: 'Feelings', w: 'HAPPY', a: ['Feliz', 'Cansado/a', 'Triste', 'Enojado/a'], c: 'Feliz' },
  { id: 'family', level: 'A1', cat: 'People', w: 'FAMILY', a: ['Familia', 'Amistad', 'Trabajo', 'Casa'], c: 'Familia' },
  { id: 'write', level: 'A1', cat: 'Actions', w: 'WRITE', a: ['Escribir', 'Hablar', 'Escuchar', 'Caminar'], c: 'Escribir' },
  { id: 'food', level: 'A1', cat: 'Food', w: 'FOOD', a: ['Comida', 'Bebida', 'Plato', 'Cocina'], c: 'Comida' },
  { id: 'today', level: 'A1', cat: 'Time', w: 'TODAY', a: ['Hoy', 'Ayer', 'Mañana', 'Ahora'], c: 'Hoy' },
  { id: 'room', level: 'A1', cat: 'Home', w: 'ROOM', a: ['Habitación', 'Ventana', 'Techo', 'Jardín'], c: 'Habitación' },
  { id: 'kitchen', level: 'A1', cat: 'Home', w: 'KITCHEN', a: ['Cocina', 'Baño', 'Sala', 'Escalera'], c: 'Cocina' },
  { id: 'teacher', level: 'A1', cat: 'Study', w: 'TEACHER', a: ['Profesor/a', 'Estudiante', 'Director/a', 'Compañero/a'], c: 'Profesor/a' },
  { id: 'student', level: 'A1', cat: 'Study', w: 'STUDENT', a: ['Estudiante', 'Profesor/a', 'Médico/a', 'Cliente'], c: 'Estudiante' },
  { id: 'work', level: 'A1', cat: 'Daily life', w: 'WORK', a: ['Trabajo', 'Descanso', 'Viaje', 'Juego'], c: 'Trabajo' },
  { id: 'eat', level: 'A1', cat: 'Actions', w: 'EAT', a: ['Comer', 'Beber', 'Dormir', 'Correr'], c: 'Comer' },
  { id: 'read', level: 'A1', cat: 'Actions', w: 'READ', a: ['Leer', 'Escribir', 'Escuchar', 'Dibujar'], c: 'Leer' },
  { id: 'night', level: 'A1', cat: 'Time', w: 'NIGHT', a: ['Noche', 'Mañana', 'Tarde', 'Día'], c: 'Noche' },
  { id: 'tired', level: 'A1', cat: 'Feelings', w: 'TIRED', a: ['Cansado/a', 'Feliz', 'Enojado/a', 'Sorprendido/a'], c: 'Cansado/a' },
  { id: 'mother', level: 'A1', cat: 'People', w: 'MOTHER', a: ['Madre', 'Hermana', 'Tía', 'Abuela'], c: 'Madre' },
  { id: 'bread', level: 'A1', cat: 'Food', w: 'BREAD', a: ['Pan', 'Arroz', 'Leche', 'Carne'], c: 'Pan' },
  { id: 'bus', level: 'A1', cat: 'Travel', w: 'BUS', a: ['Autobús', 'Avión', 'Bicicleta', 'Barco'], c: 'Autobús' },

  { id: 'travel', level: 'A2', cat: 'Travel', w: 'TRAVEL', a: ['Viajar', 'Llegar', 'Esperar', 'Comprar'], c: 'Viajar' },
  { id: 'ticket', level: 'A2', cat: 'Travel', w: 'TICKET', a: ['Boleto', 'Maleta', 'Asiento', 'Mapa'], c: 'Boleto' },
  { id: 'station', level: 'A2', cat: 'Travel', w: 'STATION', a: ['Estación', 'Aeropuerto', 'Hotel', 'Carretera'], c: 'Estación' },
  { id: 'hotel', level: 'A2', cat: 'Travel', w: 'HOTEL', a: ['Hotel', 'Hospital', 'Mercado', 'Museo'], c: 'Hotel' },
  { id: 'office', level: 'A2', cat: 'Work', w: 'OFFICE', a: ['Oficina', 'Fábrica', 'Escuela', 'Tienda'], c: 'Oficina' },
  { id: 'meeting', level: 'A2', cat: 'Work', w: 'MEETING', a: ['Reunión', 'Tarea', 'Contrato', 'Horario'], c: 'Reunión' },
  { id: 'healthy', level: 'A2', cat: 'Health', w: 'HEALTHY', a: ['Saludable', 'Enfermo/a', 'Hambriento/a', 'Ocupado/a'], c: 'Saludable' },
  { id: 'doctor', level: 'A2', cat: 'Health', w: 'DOCTOR', a: ['Médico/a', 'Enfermero/a', 'Paciente', 'Dentista'], c: 'Médico/a' },
  { id: 'weather', level: 'A2', cat: 'Daily life', w: 'WEATHER', a: ['Clima', 'Tiempo de reloj', 'Temporada', 'Temperatura'], c: 'Clima' },
  { id: 'weekend', level: 'A2', cat: 'Time', w: 'WEEKEND', a: ['Fin de semana', 'Día laborable', 'Vacaciones', 'Mes'], c: 'Fin de semana' },
  { id: 'choose', level: 'A2', cat: 'Actions', w: 'CHOOSE', a: ['Elegir', 'Cambiar', 'Buscar', 'Pagar'], c: 'Elegir' },
  { id: 'remember', level: 'A2', cat: 'Actions', w: 'REMEMBER', a: ['Recordar', 'Olvidar', 'Aprender', 'Decidir'], c: 'Recordar' },
  { id: 'because', level: 'A2', cat: 'Connectors', w: 'BECAUSE', a: ['Porque', 'Aunque', 'Entonces', 'Antes'], c: 'Porque' },
  { id: 'early', level: 'A2', cat: 'Time', w: 'EARLY', a: ['Temprano', 'Tarde', 'Rápido', 'Pronto'], c: 'Temprano' },
  { id: 'expensive', level: 'A2', cat: 'Description', w: 'EXPENSIVE', a: ['Caro/a', 'Barato/a', 'Grande', 'Nuevo/a'], c: 'Caro/a' },
  { id: 'quiet', level: 'A2', cat: 'Description', w: 'QUIET', a: ['Tranquilo/a', 'Ruidoso/a', 'Lleno/a', 'Vacío/a'], c: 'Tranquilo/a' }
];

const grammarBank = [
  { id: 'be-i', level: 'A1', topic: 'Verb to be', s: 'I ___ a student.', a: ['am', 'is', 'are'], c: 'am', e: 'Con I se usa am.' },
  { id: 'be-she', level: 'A1', topic: 'Verb to be', s: 'She ___ my friend.', a: ['am', 'is', 'are'], c: 'is', e: 'Con she se usa is.' },
  { id: 'be-they', level: 'A1', topic: 'Verb to be', s: 'They ___ at home.', a: ['am', 'is', 'are'], c: 'are', e: 'Con they se usa are.' },
  { id: 'present-he', level: 'A1', topic: 'Present simple', s: 'He ___ English every day.', a: ['study', 'studies', 'studying'], c: 'studies', e: 'En presente simple, he añade -s a study: studies.' },
  { id: 'present-we', level: 'A1', topic: 'Present simple', s: 'We ___ coffee in the morning.', a: ['drink', 'drinks', 'drinking'], c: 'drink', e: 'Con we se usa la forma base del verbo.' },
  { id: 'be-this', level: 'A1', topic: 'Verb to be', s: 'This ___ my book.', a: ['am', 'is', 'are'], c: 'is', e: 'This es singular y se combina con is.' },
  { id: 'article-an', level: 'A1', topic: 'Articles', s: 'She has ___ umbrella.', a: ['a', 'an', 'the'], c: 'an', e: 'Se usa an antes de un sonido vocálico.' },
  { id: 'article-the', level: 'A1', topic: 'Articles', s: '___ sun is bright today.', a: ['A', 'An', 'The'], c: 'The', e: 'Se usa the cuando hablamos de algo específico o único en el contexto.' },
  { id: 'pronoun-we', level: 'A1', topic: 'Pronouns', s: 'Anna and I are friends. ___ study together.', a: ['We', 'They', 'She'], c: 'We', e: 'Anna and I se reemplaza por el pronombre we.' },
  { id: 'pronoun-they', level: 'A1', topic: 'Pronouns', s: 'Tom and Lisa are here. ___ are ready.', a: ['He', 'They', 'We'], c: 'They', e: 'Dos terceras personas se pueden reemplazar por they.' },
  { id: 'prep-in', level: 'A1', topic: 'Prepositions', s: 'The keys are ___ the bag.', a: ['in', 'on', 'at'], c: 'in', e: 'In indica que algo está dentro de un lugar o recipiente.' },
  { id: 'prep-on', level: 'A1', topic: 'Prepositions', s: 'The book is ___ the table.', a: ['in', 'on', 'at'], c: 'on', e: 'On indica contacto con una superficie.' },
  { id: 'there-is', level: 'A1', topic: 'There is / are', s: 'There ___ a park near my house.', a: ['is', 'are', 'am'], c: 'is', e: 'There is se usa aquí porque park es singular.' },
  { id: 'there-are', level: 'A1', topic: 'There is / are', s: 'There ___ two chairs in the room.', a: ['is', 'are', 'be'], c: 'are', e: 'There are se usa con el plural two chairs.' },
  { id: 'present-do', level: 'A1', topic: 'Present simple', s: '___ you like coffee?', a: ['Do', 'Does', 'Are'], c: 'Do', e: 'Las preguntas en presente simple con you usan do.' },
  { id: 'present-does', level: 'A1', topic: 'Present simple', s: '___ she work here?', a: ['Do', 'Does', 'Is'], c: 'Does', e: 'Las preguntas en presente simple con she usan does y el verbo vuelve a su forma base.' },
  { id: 'modal-can', level: 'A1', topic: 'Can', s: 'I ___ swim.', a: ['can', 'cans', 'am'], c: 'can', e: 'Can expresa capacidad y no cambia con I.' },
  { id: 'possessive-my', level: 'A1', topic: 'Possessives', s: 'This is ___ phone.', a: ['my', 'me', 'I'], c: 'my', e: 'My es el adjetivo posesivo que acompaña al sustantivo phone.' },

  { id: 'past-went', level: 'A2', topic: 'Past simple', s: 'Yesterday we ___ to the market.', a: ['go', 'went', 'gone'], c: 'went', e: 'Went es el pasado simple irregular de go.' },
  { id: 'past-saw', level: 'A2', topic: 'Past simple', s: 'She ___ a movie last night.', a: ['see', 'saw', 'seen'], c: 'saw', e: 'Saw es el pasado simple irregular de see.' },
  { id: 'comparative-bigger', level: 'A2', topic: 'Comparatives', s: 'This house is ___ than that one.', a: ['big', 'bigger', 'biggest'], c: 'bigger', e: 'Para comparar dos elementos con big se usa bigger than.' },
  { id: 'comparative-expensive', level: 'A2', topic: 'Comparatives', s: 'A hotel is often ___ than a hostel.', a: ['more expensive', 'expensiver', 'most expensive'], c: 'more expensive', e: 'Con adjetivos largos como expensive se usa more + adjetivo.' },
  { id: 'going-to', level: 'A2', topic: 'Going to', s: 'I am ___ to study tonight.', a: ['go', 'going', 'went'], c: 'going', e: 'Be going to se utiliza para planes e intenciones.' },
  { id: 'present-continuous', level: 'A2', topic: 'Present continuous', s: 'They are ___ dinner now.', a: ['cook', 'cooking', 'cooked'], c: 'cooking', e: 'El presente continuo usa be + verbo en -ing para una acción en progreso.' },
  { id: 'some-any', level: 'A2', topic: 'Quantifiers', s: 'Do you have ___ questions?', a: ['some', 'any', 'much'], c: 'any', e: 'Any es común en preguntas con sustantivos contables plurales.' },
  { id: 'much-many', level: 'A2', topic: 'Quantifiers', s: 'How ___ books do you have?', a: ['much', 'many', 'some'], c: 'many', e: 'Many se usa con sustantivos contables en plural, como books.' },
  { id: 'modal-should', level: 'A2', topic: 'Should', s: 'You ___ drink more water.', a: ['should', 'shoulds', 'are'], c: 'should', e: 'Should se usa para dar consejos y mantiene la misma forma con todas las personas.' },
  { id: 'connector-because', level: 'A2', topic: 'Connectors', s: 'I stayed home ___ it was raining.', a: ['because', 'but', 'so'], c: 'because', e: 'Because introduce la razón o causa de la acción principal.' }
];

window.EnglishFastContent = { vocabBank, grammarBank };
