const vocabBank=[{w:'HOUSE',cat:'Home',a:['Casa','Mesa','Puerta','Calle'],c:'Casa'},{w:'BOOK',cat:'Study',a:['Libro','Cuaderno','Lápiz','Clase'],c:'Libro'},{w:'WATER',cat:'Daily life',a:['Agua','Comida','Vaso','Jugo'],c:'Agua'},{w:'FRIEND',cat:'People',a:['Amigo/a','Familia','Vecino/a','Profesor/a'],c:'Amigo/a'},{w:'LEARN',cat:'Actions',a:['Aprender','Escuchar','Escribir','Leer'],c:'Aprender'},{w:'SCHOOL',cat:'Study',a:['Escuela','Oficina','Tienda','Parque'],c:'Escuela'},{w:'MORNING',cat:'Time',a:['Mañana','Tarde','Noche','Semana'],c:'Mañana'},{w:'HAPPY',cat:'Feelings',a:['Feliz','Cansado/a','Triste','Enojado/a'],c:'Feliz'},{w:'FAMILY',cat:'People',a:['Familia','Amistad','Trabajo','Casa'],c:'Familia'},{w:'WRITE',cat:'Actions',a:['Escribir','Hablar','Escuchar','Caminar'],c:'Escribir'},{w:'FOOD',cat:'Daily life',a:['Comida','Bebida','Plato','Cocina'],c:'Comida'},{w:'TODAY',cat:'Time',a:['Hoy','Ayer','Mañana','Ahora'],c:'Hoy'}];
const grammarBank=[{s:'I ___ a student.',a:['am','is','are'],c:'am',e:'Con I se usa am.'},{s:'She ___ my friend.',a:['am','is','are'],c:'is',e:'Con she se usa is.'},{s:'They ___ at home.',a:['am','is','are'],c:'are',e:'Con they se usa are.'},{s:'He ___ English every day.',a:['study','studies','studying'],c:'studies',e:'En presente simple, he añade -s.'},{s:'We ___ coffee in the morning.',a:['drink','drinks','drinking'],c:'drink',e:'Con we se usa la forma base.'},{s:'This ___ my book.',a:['am','is','are'],c:'is',e:'This se usa con is.'}];
let vocabDeck=shuffle(vocabBank),vocabIndex=0,grammarDeck=shuffle(grammarBank),grammarIndex=0;
let score=Number(localStorage.getItem('englishfast-score')||0),answered=Number(localStorage.getItem('englishfast-answered')||0);
const word=document.querySelector('#questionWord'),answers=document.querySelector('#answers'),feedback=document.querySelector('#feedback'),next=document.querySelector('#nextQuestion');
const grammarSentence=document.querySelector('#grammarSentence'),grammarAnswers=document.querySelector('#grammarAnswers'),grammarFeedback=document.querySelector('#grammarFeedback'),nextGrammar=document.querySelector('#nextGrammar');
const progressScore=document.querySelector('#progressScore'),progressAnswered=document.querySelector('#progressAnswered'),progressAccuracy=document.querySelector('#progressAccuracy'),resetProgress=document.querySelector('#resetProgress');
function shuffle(list){return [...list].sort(()=>Math.random()-.5)}
function save(){localStorage.setItem('englishfast-score',score);localStorage.setItem('englishfast-answered',answered);renderProgress()}
function renderProgress(){if(progressScore)progressScore.textContent=String(score);if(progressAnswered)progressAnswered.textContent=String(answered);if(progressAccuracy)progressAccuracy.textContent=answered?`${Math.round(score/answered*100)}%`:'0%'}
function renderOptions(container,options,onSelect){container.innerHTML='';shuffle(options).forEach(option=>{const b=document.createElement('button');b.type='button';b.textContent=option;b.addEventListener('click',()=>onSelect(option,b));container.appendChild(b)})}
function renderVocab(){if(!word||!answers)return;const q=vocabDeck[vocabIndex];word.textContent=q.w;feedback.textContent=`Categoría: ${q.cat}`;renderOptions(answers,q.a,(option,button)=>checkVocab(option,button,q))}
function checkVocab(option,button,q){const buttons=[...answers.querySelectorAll('button')];if(buttons.some(b=>b.disabled))return;buttons.forEach(b=>b.disabled=true);answered+=1;if(option===q.c){score+=1;button.classList.add('correct');feedback.textContent=`Correcto. ${q.w} significa ${q.c}.`}else{button.classList.add('wrong');buttons.find(b=>b.textContent===q.c)?.classList.add('correct');feedback.textContent=`La respuesta correcta es ${q.c}.`}save()}
function renderGrammar(){if(!grammarSentence||!grammarAnswers)return;const q=grammarDeck[grammarIndex];grammarSentence.textContent=q.s;grammarFeedback.textContent='Selecciona la opción correcta.';renderOptions(grammarAnswers,q.a,(option,button)=>checkGrammar(option,button,q))}
function checkGrammar(option,button,q){const buttons=[...grammarAnswers.querySelectorAll('button')];if(buttons.some(b=>b.disabled))return;buttons.forEach(b=>b.disabled=true);answered+=1;if(option===q.c){score+=1;button.classList.add('correct');grammarFeedback.textContent=`Correcto. ${q.e}`}else{button.classList.add('wrong');buttons.find(b=>b.textContent===q.c)?.classList.add('correct');grammarFeedback.textContent=`Respuesta correcta: ${q.c}. ${q.e}`}save()}
next?.addEventListener('click',()=>{vocabIndex+=1;if(vocabIndex>=vocabDeck.length){vocabDeck=shuffle(vocabBank);vocabIndex=0}renderVocab()});
nextGrammar?.addEventListener('click',()=>{grammarIndex+=1;if(grammarIndex>=grammarDeck.length){grammarDeck=shuffle(grammarBank);grammarIndex=0}renderGrammar()});
resetProgress?.addEventListener('click',()=>{score=0;answered=0;localStorage.removeItem('englishfast-score');localStorage.removeItem('englishfast-answered');renderProgress()});
renderVocab();renderGrammar();renderProgress();
const menu=document.querySelector('.menu'),nav=document.querySelector('#nav');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav?.classList.toggle('open',!open)});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));